services:
  frontend:
    build:
      context: ./src/climatriaUI
    ports:
      - "5173:5173"
    volumes:
      - ./src/climatriaUI:/app
      - node_modules:/app/node_modules
    env_file:
      - src/climatriaUI/src/sample.env
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: app.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo-db:27017/climatria
    env_file:
      - sample.env
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aspatti1257
      - MONGO_INITDB_ROOT_PASSWORD=54yNOy0h8XczIohy

  backend:
    build:
      context: .
      dockerfile: main.Dockerfile
    volumes:
      - .:/main
    environment:
      - MONGO_URI=mongodb://mongo-db:27017/climatria
    env_file:
      - sample.env
    depends_on:
      - db

volumes:
  mongo-data:
  node_modules:
